### ISSUE TITLE
Choose a new namespace for mtRHO installation

### ISSUE THREAD

**Issue by jmontleon** [konveyor/crane-operator#22]
- mtRHO and MTC both request to be installed in the openshift-migration namespace.
- Due to a requirement for different OLM install modes to watch own vs all namespaces they cannot coexist in the one namespace.
- MTC must be restricted to watching it's own namespace.
- mtRHO must watch all namespaces so it can see some cluster scoped resources.

**Comment by JaydipGabani** [comment]
Closing as this is now fixed with #35
